"""Command repository — PostgreSQL data access for the control_commands table.

V1 command types: CREATE_DATASET_BUILD, REBUILD_DATASET_BUILD, DELETE_DATASET_BUILD,
                  START_ATTEMPT, ABORT_ATTEMPT, REQUEST_CHECKPOINT
"""

from __future__ import annotations

import json
import logging
import uuid
from datetime import datetime
from typing import Any

import psycopg
from psycopg.rows import dict_row

logger = logging.getLogger(__name__)

COMMAND_TYPES = {
    "CREATE_DATASET_BUILD",
    "REBUILD_DATASET_BUILD",
    "DELETE_DATASET_BUILD",
    "START_ATTEMPT",
    "ABORT_ATTEMPT",
    "REQUEST_CHECKPOINT",
}

COMMAND_STATES = {"PENDING", "ACCEPTED", "DEFERRED", "SUCCEEDED", "REJECTED", "FAILED"}
TERMINAL_COMMAND_STATES = {"SUCCEEDED", "REJECTED", "FAILED"}


def _row_to_dict(row: dict) -> dict:
    return dict(row)


def create_command(
    conn: psycopg.Connection,
    *,
    command_id: str,  # UUID string, generated by caller before any network calls
    command_type: str,
    target_type: str,
    target_id: str | None = None,
    request: dict | None = None,
    requester_context: dict | None = None,
    requested_at: datetime,
) -> dict:
    """Persist a PENDING command record.

    Per data-flow spec: command must be persisted BEFORE being sent to Runtime.
    command_id is stable across retries.
    """
    request = request or {}
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            """
            INSERT INTO control_commands (
                command_id, command_type, target_type, target_id,
                state, request_jsonb, requester_context_jsonb, requested_at
            ) VALUES (%s, %s, %s, %s, 'PENDING', %s, %s, %s)
            RETURNING *
            """,
            (
                command_id, command_type, target_type, target_id,
                json.dumps(request), json.dumps(requester_context) if requester_context else None,
                requested_at,
            ),
        )
        row = cur.fetchone()
    return _row_to_dict(row)


def update_command_state(
    conn: psycopg.Connection,
    command_id: str,
    new_state: str,
    *,
    result: dict | None = None,
    dispatched_at: datetime | None = None,
    completed_at: datetime | None = None,
) -> dict | None:
    sets = ["state = %s"]
    params: list[Any] = [new_state]

    if dispatched_at is not None:
        sets.append("dispatched_at = %s")
        params.append(dispatched_at)
    if completed_at is not None:
        sets.append("completed_at = %s")
        params.append(completed_at)
    if result is not None:
        sets.append("result_jsonb = %s")
        params.append(json.dumps(result))

    params.append(command_id)
    sql = f"UPDATE control_commands SET {', '.join(sets)} WHERE command_id = %s RETURNING *"

    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(sql, params)
        row = cur.fetchone()
    return _row_to_dict(row) if row else None


def get_command(conn: psycopg.Connection, command_id: str) -> dict | None:
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            "SELECT * FROM control_commands WHERE command_id = %s", (command_id,)
        )
        row = cur.fetchone()
    return _row_to_dict(row) if row else None


def list_commands(
    conn: psycopg.Connection,
    *,
    command_type: str | None = None,
    state: str | None = None,
    target_type: str | None = None,
    target_id: str | None = None,
    limit: int = 50,
    cursor: str | None = None,
) -> list[dict]:
    conditions = []
    params: list[Any] = []

    if command_type:
        conditions.append("command_type = %s")
        params.append(command_type)
    if state:
        conditions.append("state = %s")
        params.append(state)
    if target_type:
        conditions.append("target_type = %s")
        params.append(target_type)
    if target_id:
        conditions.append("target_id = %s")
        params.append(target_id)

    if cursor:
        try:
            ts_str, cid = cursor.split("|", 1)
            conditions.append("(requested_at, command_id) < (%s::timestamptz, %s::uuid)")
            params.extend([ts_str, cid])
        except ValueError:
            pass

    where = ("WHERE " + " AND ".join(conditions)) if conditions else ""
    params.append(limit)

    sql = f"""
        SELECT * FROM control_commands
        {where}
        ORDER BY requested_at DESC, command_id DESC
        LIMIT %s
    """
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(sql, params)
        rows = cur.fetchall()
    return [_row_to_dict(r) for r in rows]
