"""Agent protocol package.

Exports wire schemas, payloads, and envelope parsers for Backend <-> Node Agent communication.
Zero runtime/backend/worker/torch/db dependencies. Pure wire framing.
"""

from __future__ import annotations

from pbl4.agent_protocol.messages import (
    ACTIVE_ALLOCATION_LOCAL_STATES,
    AGENT_PROTOCOL_VERSION,
    COMMAND_STATUS_ACCEPTED,
    COMMAND_STATUS_REJECTED,
    COMMAND_TYPE_START_WORKER,
    COMMAND_TYPE_STOP_WORKER,
    ERROR_CODE_ALLOCATION_ALREADY_ACTIVE,
    ERROR_CODE_ALLOCATION_NOT_FOUND,
    ERROR_CODE_INVALID_COMMAND_PAYLOAD,
    ERROR_CODE_UNKNOWN_COMMAND_TYPE,
    ERROR_CODE_WORKER_SPAWN_FAILED,
    ERROR_CODE_WORKER_STOP_FAILED,
    MESSAGE_TYPE_AGENT_HELLO,
    MESSAGE_TYPE_COMMAND,
    MESSAGE_TYPE_COMMAND_ACK,
    MESSAGE_TYPE_HEARTBEAT,
    MESSAGE_TYPE_HELLO_ACK,
    MESSAGE_TYPE_RESOURCE_SNAPSHOT,
    MESSAGE_TYPE_WORKER_STATUS,
    VALID_COMMAND_STATUSES,
    VALID_COMMAND_TYPES,
    VALID_MESSAGE_TYPES,
    VALID_WORKER_ACTUAL_STATES,
    WORKER_ACTUAL_STATE_ENDED,
    WORKER_ACTUAL_STATE_FAILED,
    WORKER_ACTUAL_STATE_STARTED,
    ActiveAllocationItem,
    AgentEnvelope,
    AgentHelloPayload,
    AgentMessageError,
    AgentPayload,
    CommandAckPayload,
    GpuSnapshotItem,
    HeartbeatPayload,
    HelloAckPayload,
    ResourceSnapshotPayload,
    StartWorkerPayload,
    StopWorkerPayload,
    WorkerStatusPayload,
    parse_agent_envelope,
)

__all__ = [
    "ACTIVE_ALLOCATION_LOCAL_STATES",
    "AGENT_PROTOCOL_VERSION",
    "COMMAND_STATUS_ACCEPTED",
    "COMMAND_STATUS_REJECTED",
    "COMMAND_TYPE_START_WORKER",
    "COMMAND_TYPE_STOP_WORKER",
    "ERROR_CODE_ALLOCATION_ALREADY_ACTIVE",
    "ERROR_CODE_ALLOCATION_NOT_FOUND",
    "ERROR_CODE_INVALID_COMMAND_PAYLOAD",
    "ERROR_CODE_UNKNOWN_COMMAND_TYPE",
    "ERROR_CODE_WORKER_SPAWN_FAILED",
    "ERROR_CODE_WORKER_STOP_FAILED",
    "MESSAGE_TYPE_AGENT_HELLO",
    "MESSAGE_TYPE_COMMAND",
    "MESSAGE_TYPE_COMMAND_ACK",
    "MESSAGE_TYPE_HEARTBEAT",
    "MESSAGE_TYPE_HELLO_ACK",
    "MESSAGE_TYPE_RESOURCE_SNAPSHOT",
    "MESSAGE_TYPE_WORKER_STATUS",
    "VALID_COMMAND_STATUSES",
    "VALID_COMMAND_TYPES",
    "VALID_MESSAGE_TYPES",
    "VALID_WORKER_ACTUAL_STATES",
    "WORKER_ACTUAL_STATE_ENDED",
    "WORKER_ACTUAL_STATE_FAILED",
    "WORKER_ACTUAL_STATE_STARTED",
    "ActiveAllocationItem",
    "AgentEnvelope",
    "AgentHelloPayload",
    "AgentMessageError",
    "AgentPayload",
    "CommandAckPayload",
    "GpuSnapshotItem",
    "HeartbeatPayload",
    "HelloAckPayload",
    "ResourceSnapshotPayload",
    "StartWorkerPayload",
    "StopWorkerPayload",
    "WorkerStatusPayload",
    "parse_agent_envelope",
]
